# Generated by Django 4.2.7 on 2024-12-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_chapter_chapter_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
