# Generated by Django 4.2.7 on 2024-12-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_remove_story_genre_delete_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
