# Generated by Django 4.2.7 on 2024-12-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_remove_chapter_text_scene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='slug',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(unique=True),
        ),
    ]
